version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=DEBUG
    ports:
      - '80:80'
      - '81:8080'
      - '8025:8025'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      frontend: {}

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mail.test'
      - 'traefik.docker.network=docker-localhost_frontend'
    networks:
      frontend: {}
      backend: {}

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.test'
    networks:
      frontend: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
