http:
  routers:
    traefik:
      rule: "Host(`traefik.d.test`)"
      service: "api@internal"
      tls:
        domains:
          - main: "d.test"
            sans:
              - "*.d.test"
          - main: "d.uno"
            sans:
              - "*.d.uno"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
